### ISSUE TITLE
Seg Fault in network_stream.go

### ISSUE THREAD

**Issue by FPurchess** [kubescape/node-agent#580]
# Description
When running the node-agent, we receive the following error message:
```
{"level":"info","ts":"2025-06-07T20:19:34Z","msg":"credentials loaded","accountLength":0}
{"level":"info","ts":"2025-06-07T20:19:34Z","msg":"Kubernetes mode is true"}
{"level":"info","ts":"2025-06-07T20:19:34Z","msg":"starting health manager","port":7888}
W0607 20:19:34.530574 2438595 client_config.go:667] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"level":"error","ts":"2025-06-07T20:19:34Z","msg":"error getting cloud metadata","error":"unknown cloud provider for node **REDACTED[nodename]**: rke2://**REDACTED[nodename]**"}
{"level":"info","ts":"2025-06-07T20:19:34Z","msg":"exporters initialized"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=*** pc=***]

goroutine 1 [running]:                                                                                                                                                                   
github.com/kubescape/node-agent/pkg/networkstream/v1.NewNetworkStream({_, _}, {{****, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...)
    /work/pkg/networkstream/v1/network_stream.go:68 +0x206
main.main()
    /work/cmd/main.go:291
```

We're using the latest available version of the official kubescape helm chart (`kubescape-operator-1.27.8`).

# Environment
OS: Ubuntu 24.04 LTS
Agent-Version: 0.2.343
 
# Additional Context
Our values.yaml
```
clusterName: **redacted**
ksNamespace: **redacted**
ksLabel: **redacted**
capabilities:
  # ====== configuration scanning related capabilities ======
  #
  # Default configuration scanning setup
  configurationScan: enable
  # Continuous Scanning continuously evaluates the security posture of your cluster.
  continuousScan: disable
  nodeScan: enable

  # ====== Image vulnerabilities scanning related capabilities ======
  #
  vulnerabilityScan: enable
  relevancy: enable
  # Generate VEX documents alongside the image vulnerabilities report (experimental)
  vexGeneration: disable

  # ====== Runtime related capabilities ======
  #
  runtimeObservability: enable
  networkPolicyService: enable
  runtimeDetection: enable
  malwareDetection: enable
  nodeProfileService: disable
  seccompProfileService: enable

  # ====== Other capabilities ======
  #
  # This is an experimental capability with an elevated security risk. Read the
  # matching docs before enabling.
  autoUpgrading: disable
  prometheusExporter: enable
  # seccompGenerator: disable

#extra capability - service discovery option
serviceScanConfig:
  enabled : false
  interval: 1h

configurations:
  persistence: enable

  # Enable Prometheus annotations, to allow open-source Prometheus (not operator) to scrape metrics
  prometheusAnnotations: enable

persistence:
  storageClass: **redacted**
  accessMode: ReadWriteOnce
  size:
    backingStorage: 20Gi
    kubevuln: 10Gi

storage:
  nodeSelector:
    node-type: **redacted**

kubescape:
  serviceMonitor:
    enabled: true

nodeAgent:
  resources:
    requests:
      cpu: 100m
      memory: 180Mi
    limits:
      cpu: 1000m
      memory: 2500Mi
  serviceMonitor:
    enabled: true
```
